In [1]:
import numpy as np


In [2]:
print(np.__version__)

2.2.2


In [3]:
# 1 Create a 1D NumPy array from a Python list
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D NumPy array:")
print(arr_1d)

# 2 Create a 2D NumPy array of shape (3x3) using numbers from 1 to 9
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("\n2D NumPy array:")
print(arr_2d)

# 3 Generate an array of 10 evenly spaced values between 0 and 5
arr_spaced = np.linspace(0, 5, 10)
print("\nEvenly spaced array:")
print(arr_spaced)


1D NumPy array:
[1 2 3 4 5]

2D NumPy array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Evenly spaced array:
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [4]:
# Creating the 2D NumPy array
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
# 1 Access the element in the second row, third column
element = arr_2d[1, 2]  # Indexing starts from 0
print("Element in second row, third column:", element)

# 2 Slice the first two rows and the first two columns
sliced_arr = arr_2d[:2, :2]  # Rows: 0-1, Columns: 0-1
print("\nSliced array (first two rows and columns):")
print(sliced_arr)

# 3 Modify the value in the last row and first column to 100
arr_2d[2, 0] = 100  # Changing the element at row index 2, column index 0
print("\nModified array:")
print(arr_2d)


Element in second row, third column: 6

Sliced array (first two rows and columns):
[[1 2]
 [4 5]]

Modified array:
[[  1   2   3]
 [  4   5   6]
 [100   8   9]]


In [6]:

# 1 Find the shape, size, and data type of the 2D array
shape = arr_2d.shape  # Shape of the array (rows, columns)
size = arr_2d.size    # Total number of elements
dtype = arr_2d.dtype  # Data type of elements

print("Shape of 2D array:", shape)
print("Size of 2D array:", size)
print("Data type of 2D array:", dtype)

# Creating a 1D NumPy array
arr_1d = np.array([1, 2, 3, 4, 5])

# 2 Change the 1D array into a 2D array of shape (5,1)
arr_2d_reshaped = arr_1d.reshape(5, 1)
print("\nReshaped 1D array into 2D (5,1):")
print(arr_2d_reshaped)

# 3 Flatten a multi-dimensional array back into a 1D array
arr_flattened = arr_2d.flatten()
print("\nFlattened array:")
print(arr_flattened)


Shape of 2D array: (3, 3)
Size of 2D array: 9
Data type of 2D array: int64

Reshaped 1D array into 2D (5,1):
[[1]
 [2]
 [3]
 [4]
 [5]]

Flattened array:
[1 2 3 4 5 6 7 8 9]


In [7]:

# 1 Add 5 to every element in the 1D array
arr_1d_added = arr_1d + 5
print("1D array after adding 5:")
print(arr_1d_added)

# Creating the 2D array
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])

# 2 Multiply the 2D array by 3
arr_2d_multiplied = arr_2d * 3
print("\n2D array after multiplication by 3:")
print(arr_2d_multiplied)

A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

# 3 Perform matrix multiplication
matrix_product = np.dot(A, B)  # Or A @ B
print("\nMatrix multiplication result (A * B):")
print(matrix_product)


1D array after adding 5:
[ 6  7  8  9 10]

2D array after multiplication by 3:
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]

Matrix multiplication result (A * B):
[[19 22]
 [43 50]]


In [9]:

# 1 Create a 3x3 matrix of ones
matrix_ones = np.ones((3, 3))  # Creates a 3x3 matrix filled with ones
print("3x3 Matrix of ones:")
print(matrix_ones)

# 2 Create a 1D array of length 3
array_1d = np.array([1, 2, 3])  # 1D array of length 3
print("\n1D array:")
print(array_1d)

# 3 Add the 1D array to each row of the matrix using broadcasting
result_matrix = matrix_ones + array_1d  # Broadcasting happens here
print("\nResult after broadcasting:")
print(result_matrix)


3x3 Matrix of ones:
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]

1D array:
[1 2 3]

Result after broadcasting:
[[2. 3. 4.]
 [2. 3. 4.]
 [2. 3. 4.]]
