In [7]:
import numpy as np


In [8]:
a = np.array([1,2,3,4,5])

In [9]:
a

array([1, 2, 3, 4, 5])

In [10]:
b = np.random.randint(1,9,(3,3))

In [11]:
b

array([[3, 7, 5],
       [1, 8, 7],
       [1, 5, 5]], dtype=int32)

In [17]:
b[2][2]

np.int32(5)

In [20]:
b[::2, 0:2]

array([[3, 7],
       [1, 5]], dtype=int32)

In [21]:
b[2,0] = 100


In [22]:
b

array([[  3,   7,   5],
       [  1,   8,   7],
       [100,   5,   5]], dtype=int32)

In [23]:
b.shape

(3, 3)

In [26]:
c = a.reshape(5,1)

In [27]:
c

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [29]:
c = a.flatten()

In [30]:
c

array([1, 2, 3, 4, 5])