In [1]:
!pip install numpy



[notice] A new release of pip is available: 24.2 -> 25.0.1
[notice] To update, run: python.exe -m pip install --upgrade pip


In [2]:
import numpy as np

In [22]:
a = np.array([1,2,3,4,5,])

In [23]:
a

array([1, 2, 3, 4, 5])

In [25]:
a.shape

(5,)

In [26]:
b = np.random.randint(2,30,(5,3))

In [18]:
b


array([[16, 24, 15],
       [ 8, 18, 22],
       [ 9, 19,  3],
       [15, 14, 10],
       [29,  6, 29]], dtype=int32)

In [44]:
b.ndim

2

In [45]:
np.zeros(shape = (5,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [48]:
m = np.array([1,2,3,4,5,6])

In [49]:
m


array([1, 2, 3, 4, 5, 6])

In [81]:
#2D Dimension
n = np.random.randint(0,10,(5,4))

In [82]:
n


array([[1, 9, 8, 8],
       [9, 7, 0, 3],
       [4, 8, 6, 4],
       [1, 7, 8, 8],
       [1, 3, 2, 9]], dtype=int32)

In [83]:
n[1][3]

np.int32(3)

In [84]:
n [2][3]

np.int32(4)

In [85]:
#3D Dimension
o = np.random.randint(7,30,(4,3,3))

In [86]:
o


array([[[10, 15, 29],
        [21, 19, 16],
        [ 9, 11, 21]],

       [[16,  7, 13],
        [ 9, 12, 16],
        [18, 24, 26]],

       [[ 8,  8, 11],
        [24, 18, 18],
        [23, 24, 22]],

       [[ 8, 14, 13],
        [11, 12, 10],
        [17, 11, 17]]], dtype=int32)

In [87]:
o [3][1][1]

np.int32(12)

In [88]:
o [1][1][1]

np.int32(12)

In [89]:
#Slicing in 1D Array 
m


array([1, 2, 3, 4, 5, 6])

In [90]:
m[1:-1:2]

array([2, 4])

In [91]:
#Slicing 2D array
n

array([[1, 9, 8, 8],
       [9, 7, 0, 3],
       [4, 8, 6, 4],
       [1, 7, 8, 8],
       [1, 3, 2, 9]], dtype=int32)

In [93]:
#Index Slicing
n[::2][1][2]

np.int32(6)

In [98]:
#Row Slicing
n[::2]

array([[1, 9, 8, 8],
       [4, 8, 6, 4],
       [1, 3, 2, 9]], dtype=int32)

In [99]:
#Column Slicing
n[::1 , 1:3]

array([[9, 8],
       [7, 0],
       [8, 6],
       [7, 8],
       [3, 2]], dtype=int32)

In [127]:
#Boolean or Mask Indexing 
a = np.random.randint(2,10,(4,3))

In [128]:
a

array([[3, 7, 8],
       [7, 2, 2],
       [8, 2, 2],
       [4, 3, 7]], dtype=int32)

In [129]:
 mask = a%2==0

In [130]:
mask


array([[False, False,  True],
       [False,  True,  True],
       [ True,  True,  True],
       [ True, False, False]])

In [131]:
a[mask]

array([8, 2, 2, 8, 2, 2, 4], dtype=int32)